# Generated by Django 2.2.10 on 2020-11-12 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_auto_20201112_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Question', verbose_name='К вопросу'),
        ),
        migrations.AlterField(
            model_name='question',
            name='from_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Poll', verbose_name='К опросу'),
        ),
    ]
