# Generated by Django 2.2.10 on 2020-11-16 06:43

import datetime
from django.db import migrations, models
import pools.models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_poll_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_finish',
            field=models.DateField(default=datetime.date(2020, 11, 16), verbose_name='Дата завершения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='date_start',
            field=models.DateField(default=datetime.date(2020, 11, 16), verbose_name='Дата начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.CharField(default='', max_length=1024, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[(1, 'one_choice'), (2, 'multiple_choice'), (3, 'free_text')], default=pools.models.QuestionTypes(1), max_length=64, verbose_name='Тип ответа на вопрос'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='final_text',
            field=models.CharField(default='', max_length=1024, verbose_name='Сообщение о завершении опроса'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='welcome_text',
            field=models.CharField(default='', max_length=1024, verbose_name='Приветственное сообщение в начале опроса'),
        ),
    ]
