# Generated by Django 2.2.10 on 2020-11-12 20:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.CharField(max_length=1024, verbose_name='Приветственное сообщение в начале опроса')),
                ('final_text', models.CharField(max_length=1024, verbose_name='Сообщение о завершении опроса')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='from_poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
            preserve_default=False,
        ),
    ]
