# Generated by Django 2.2.10 on 2020-11-17 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201116_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=256, verbose_name='Текст ответа')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='from_poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.Poll', verbose_name='К опросу'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='possibleanswer',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_answers', to='polls.Question', verbose_name='К вопросу'),
        ),
    ]
