# Generated by Django 2.2.10 on 2020-11-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20201117_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelTable(
            name='poll',
            table='pools',
        ),
    ]
