# Generated by Django 2.2.10 on 2020-11-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20201119_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possibleanswer',
            options={'verbose_name': 'Возможный ответ', 'verbose_name_plural': 'Возможные ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelTable(
            name='possibleanswer',
            table='possible_answers',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
